apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "true"
    release.appstudio.openshift.io/standing-attribution: "true"
    release.appstudio.openshift.io/releasePlanAdmission: my-definitions-tasks
  name: publish-bundle
  namespace: cqi-tenant
spec:
  application: my-definitions
  # data:
  #   mapping:
  #     components:
  #     - name: my-definitions-task-init-v01-ew02
  #       repository: quay.io/mytestworkload/my-tekton-catalog/task-init
  #       tags:
  #       - "0.1"
  #       - latest
  #       - "{{ git_sha }}"
  #       - "{{ git_short_sha }}"
  #       - "{{ digest_sha }}"
  # tenantPipeline:
  #   pipelineRef:
  #     resolver: git
  #     params:
  #     - name: url
  #       value: https://github.com/konflux-ci/release-service-catalog.git
  #     - name: revision
  #       value: development
  #     - name: pathInRepo
  #       value: pipelines/managed/push-tekton-task-bundles-to-external-registry/push-tekton-task-bundles-to-external-registry.yaml
  #   serviceAccountName: build-pipeline-my-definitions-task-init-v01-ew02
