---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  generateName: my-definitions-task-init-v01-
  namespace: cqi-tenant
  labels:
    release.appstudio.openshift.io/automated: "false"
    release.appstudio.openshift.io/author: cqi
spec:
  gracePeriodDays: 2
  releasePlan: publish-bundle
  snapshot:  # replace with real snapshot name
