apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: my-tenant-pipeline
spec:
  params:
    - name: release
      type: string
    - name: releasePlan
      type: string
    - name: snapshot
      type: string
  tasks:
    - name: publish-resources
      taskSpec:
       steps:
         - name: publish
           image: registry.access.redhat.com/ubi10/ubi-minimal@sha256:5a57b4c2509df8df587e19cc7c2d9cfa45b012139f5decd77f942daeb2334228
           script: |
             #!/usr/bin/env bash
             set -euo pipefail
             echo "Release: $(params.release)"
             echo "ReleasePlan: $(params.releasePlan)"
             echo "Snapshot: $(params.snapshot)"
