apiVersion: tekton.dev/v1
kind: Task
metadata:
  labels:
    app.kubernetes.io/version: "0.1"
    build.appstudio.redhat.com/build_type: "docker"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: "konflux"
  name: copy-files
spec:
  description: Copy files
  params:
  - name: filenames
    type: array
    default: []
  steps:
  - name: copy-files
    image: quay.io/konflux-ci/tools@sha256:976b26b3f62abaa3b3178579dca43bc9222013100828192bbb588508b048f205
    script: |
      #!/usr/bin/env bash
      set -euo pipefail
      echo copy files
