apiVersion: tekton.dev/v1
kind: Task
metadata:
  labels:
    app.kubernetes.io/version: "0.1"
    build.appstudio.redhat.com/build_type: "docker"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: "konflux"
  name: copy-files
spec:
  description: Copy files
  params:
  - name: filenames
    type: array
    default: []
  steps:
  - name: copy-files
    image: quay.io/konflux-ci/tools@sha256:5ef2b700ff5a1543a4aaae11b606fd030a31c812f079cf7aa058bd8f9c7b5da9
    script: |
      #!/usr/bin/env bash
      set -euo pipefail
      echo copy files
