apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/my-konflux-stuff/my-definitions?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main" && ( "tasks/init/0.1/***".pathChanged() || ".tekton/my-definitions-task-init-v01-ew02-push.yaml".pathChanged()
      )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: my-definitions
    appstudio.openshift.io/component: my-definitions-task-init-v01-ew02
    pipelines.appstudio.openshift.io/type: build
  name: my-definitions-task-init-v01-ew02-on-push
  namespace: cqi-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/cqi-tenant/my-definitions-task-init-v01-ew02:{{revision}}
  - name: dockerfile
    value: Dockerfile
  - name: path-context
    value: tasks/init/0.1
  pipelineRef:
    name: build-pipeline
  taskRunTemplate:
    serviceAccountName: build-pipeline-my-definitions-task-init-v01-ew02
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
