apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cqi-tenant
resources:
- onboard.yaml
- integration-tests/init.yaml
- releases/tekton-bundle-standard.yaml
- releases/release.yaml