apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: test-pipeline
spec:
  params:
  - description: 'Snapshot of the application'
    name: SNAPSHOT
    default: ''
    type: string
  tasks:
  - name: test
    params:
      - name: SNAPSHOT
        value: $(params.SNAPSHOT)
      - name: test-name
        value: $(context.pipelineRun.name)
    taskSpec:
      steps:
      - name: test
        image: registry.access.redhat.com/ubi9/ubi-minimal:@sha256:8d905a93f1392d4a8f7fb906bd49bf540290674b28d82de3536bb4d0898bf9d7
        script: |
          echo "test test test ..."

