---
# <TEMPLATED FILE!>
# This file comes from the templates at https://github.com/konflux-ci/task-repo-shared-ci.
# Please consider sending a PR upstream instead of editing the file directly.
# See the SHARED-CI.md document in this repo for more details.

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
