# <TEMPLATED FILE!>
# This file comes from the templates at https://github.com/konflux-ci/task-repo-shared-ci.
# Please consider sending a PR upstream instead of editing the file directly.
# See the SHARED-CI.md document in this repo for more details.

name: Validate PR - kustomize manifests
'on':
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]
jobs:
  kustomize-build:
    name: Check Kustomize Build of Task
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Install oc
        run: |
          set -euo pipefail
          url=https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/latest-4.17/openshift-client-linux.tar.gz
          if ! which oc; then
            curl --fail --no-progress-meter -L "$url" | gzip -cd | sudo -- tar -x -C /usr/bin oc
          fi
      - name: Validate Manifests
        run: hack/verify-manifests.sh
