---
# <TEMPLATED FILE!>
# This file comes from the templates at https://github.com/konflux-ci/task-repo-shared-ci.
# Please consider sending a PR upstream instead of editing the file directly.
# See the SHARED-CI.md document in this repo for more details.

name: Check Tekton Tasks

'on':
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]

jobs:
  check:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.12.0
        with:
          cluster_name: kind

      - name: Set up Tekton
        id: setup-tektoncd
        uses: tektoncd/actions/setup-tektoncd@main
        with:
          pipeline_version: latest
        continue-on-error: true

      - name: Describe setup-tektoncd failure
        if: steps.setup-tektoncd.outcome != 'success'
        run: |
          curl -s https://api.github.com/repos/tektoncd/pipeline/releases/latest | jq
          echo "The previous action setup-tektoncd seems to have failed due to a known issue caused by hitting the rate-limit"
          echo "For more information, follow the following issue: https://github.com/tektoncd/actions/issues/9"
          echo "The only known workaround at the moment is to re-run this workflow."
          exit 1

      - name: Apply all Tasks
        run: |
          set -e
          ./.github/scripts/check_tekton_tasks.sh
