# <TEMPLATED FILE!>
# This file comes from the templates at https://github.com/konflux-ci/task-repo-shared-ci.
# Please consider sending a PR upstream instead of editing the file directly.
# See the SHARED-CI.md document in this repo for more details.

name: "Lint Tekton Tasks"

'on':
  pull_request:
    branches: [main]
    paths:
      - 'task/**/*.yaml'
  merge_group:
    types: [checks_requested]

jobs:
  lint-disallowed-params:
    name: "Check for insecure params in tasks"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v4

      - name: "Install yq"
        uses: mikefarah/yq@v4
        with:
          # Version from https://github.com/mikefarah/yq/releases
          version: 'v4.47.1'

      - name: "Run linter script"
        id: linter-script
        run: |
          #!/bin/bash
          for task in $(find task -name '*.yaml'); do
            if yq '.spec?.steps[] | .script' $task | grep -q '\$(params\.'; then
              FAILED_TASKS="$FAILED_TASKS $task"
            fi
          done
          if [ -n "$FAILED_TASKS" ]; then
            echo "Tasks contains params in script section (https://github.com/tektoncd/catalog/blob/main/recommendations.md#dont-use-interpolation-in-scripts-or-string-arguments)"
            echo "This is disallowed as it can lead to arbitrary code execution"
            echo $FAILED_TASKS | tr ' ' '\n' | sort
            exit 1
          fi
